"""Add user data to payment

Revision ID: 3a5b8d7e6f4c
Revises: 2c50b151f060
Create Date: 2025-08-18 20:15:00.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5b8d7e6f4c'
down_revision = '2c50b151f060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('fio', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('iin', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'phone')
    op.drop_column('payments', 'iin')
    op.drop_column('payments', 'fio')
    # ### end Alembic commands ###
